apiVersion: apps/v1
kind: Deployment
metadata:
  name: heeaws-ops-suite-api
  namespace: cloud-cell
  labels:
    app: heeaws-ops-suite-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heeaws-ops-suite-api
  template:
    metadata:
      labels:
        app: heeaws-ops-suite-api
    spec:
      containers:
      - name: api
        image: heeaws-ops-suite:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: heeaws-ops-suite-api-service
  namespace: cloud-cell
  labels:
    app: heeaws-ops-suite-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: heeaws-ops-suite-api